services:
  backend:
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile
    container_name: backend_container
    working_dir: /app
    ports:
      - "8600:8600"
    volumes:
      - ./backend:/app
    command: sh -c "composer install && php -S 0.0.0.0:8600 -t public"
    environment:
      DB_HOST: iutinfo-2410-01.unilim.fr
      DB_PORT: 3306
      DB_DATABASE: db_sae_previ
      DB_USERNAME: phpmyadmin
      DB_PASSWORD: G389d}i^6uGJ-6K)n
    networks:
      - sae_previsionnel
    restart: always

networks:
  sae_previsionnel:
    driver: bridge
