services:
  backend:
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile
    container_name: backend_container
    working_dir: /app
    ports:
      - "8600:8600"
    volumes:
      - ./backend:/app
    command: sh -c "composer install && php -S 0.0.0.0:8600 -t public"
    environment:
      DB_HOST: db  # "db" doit correspondre au nom du service MySQL
      DB_PORT: 3306
      DB_DATABASE: db_sae_previ
      DB_USERNAME: phpmyadmin
      DB_PASSWORD: G389d}i^6uGJ-6K)n
    networks:
      - sae_previsionnel
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: G389d}i^6uGJ-6K)n
    ports:
      - "3306:3306"
    networks:
      - sae_previsionnel
    restart: always
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: db  # Utilisez le nom de service "db" pour accéder au conteneur MySQL
      PMA_PORT: 3306
      PMA_USER: phpmyadmin
      PMA_PASSWORD: G389d}i^6uGJ-6K)n
    ports:
      - "8080:80"
    networks:
      - sae_previsionnel
    restart: always

networks:
  sae_previsionnel:
    driver: bridge

volumes:
  db_data:
