<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNtWEmow\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNtWEmow/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNtWEmow.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNtWEmow\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNtWEmow\App_KernelDevDebugContainer([
    'container.build_hash' => 'NtWEmow',
    'container.build_id' => '5f589e31',
    'container.build_time' => 1732028478,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNtWEmow');
